### ISSUE TITLE
Unable to find assembly '03-PhiData'.

### ISSUE THREAD

**Issue by Faabvk** [Longwelwind/Phi#40]
Just as it says. When I run Phi Server it starts and I can connect but once I connect I get that error. 
```
PS D:\Downloads\PhiServer> .\PhiServer.exe
[17-12-2018 19:08:24] [INFO] Server launched on port 16180
[17-12-2018 19:08:29] [INFO] Connection from a06adefdc962404b9ae9ace8284e855d
17-12-2018 19:08:29|Error|WebSocket.message|System.Runtime.Serialization.SerializationException: Unable to find assembly '03-PhiData'.
                             at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
                             at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
                             at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
                             at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
                             at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
                             at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
                             at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
                             at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
                             at PhiClient.Packet.Deserialize(Byte[] data, RealmData realmData, User user) in D:\Documents\Projects\Phi\PhiData\Packet.cs:line 34
                             at PhiServer.Program.MessageCallback(ServerClient client, Byte[] data) in D:\Documents\Projects\Phi\PhiServer\Program.cs:line 106
                             at SocketLibrary.Server.MessageCallback(ServerClient client, Byte[] data) in D:\Documents\Projects\Phi\SocketLibrary\Server.cs:line 56
                             at SocketLibrary.ServerClient.OnMessage(MessageEventArgs e) in D:\Documents\Projects\Phi\SocketLibrary\ServerClient.cs:line 35
                             at WebSocketSharp.Ext.Emit[TEventArgs](EventHandler`1 eventHandler, Object sender, TEventArgs e)
                             at WebSocketSharp.WebSocket.messages(MessageEventArgs e)
```

**Comment by Faerye0** [comment]
Did you resolved the problem?

**Comment by Shorent** [comment]
Am getting the same problem, it looks like its trying to fetch information that doesn't exist in lines 12-13

**Comment by zzzz465** [comment]
I got this bug too.

**Comment by ajsnyde** [comment]
Same

**Comment by Trugath** [comment]
You are using Andrew-Fall's client on the steam workshop if you are getting this error. If you want to use the workshop client then use Andrew's server at https://github.com/Andrew-Fall/PhiServer
Otherwise use the client for the version of the server you wish to use instead.
